### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by NoorAgario** [whxaxes/slither#2]
C:\Users\Anony\Desktop\slither-master\src>npm install
npm WARN package.json slither@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path C:\Users\Anony\AppData\Roaming\npm-cache\eslint\2.9.0\package.tgz.767635979
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\Anony\AppData\Roaming\npm-cache\eslint\2.9.0\package.tgz.767635979' -> 'C:\Users\Anony\AppData\Roaming\npm-cache\eslint\2.9.0\package.tgz'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\Anony\AppData\Roaming\npm-cache\eslint\2.9.0\package.tgz.767635979' -> 'C:\Users\Anony\AppData\Roaming\npm-cache\eslint\2.9.0\package.tgz']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\Users\Anony\AppData\Roaming\npm-cache\eslint\2.9.0\package.tgz.767635979',
npm ERR!   dest: 'C:\Users\Anony\AppData\Roaming\npm-cache\eslint\2.9.0\package.tgz',
npm ERR!   parent: 'slither' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Anony\Desktop\slither-master\src\npm-debug.log

C:\Users\Anony\Desktop\slither-master\src>

**Comment by NoorAgario** [comment]
help plz @whxaxes

**Comment by whxaxes** [comment]
See http://stackoverflow.com/questions/22325031/npm-please-try-using-this-command-again-as-root-administrator
