### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Logan7432** [whxaxes/slither#4]
Is there a way to set it up to play on same server with freiends?

**Comment by whxaxes** [comment]
Sorry, server side is unsupported yet

**Comment by dmbekker** [comment]
Wil a server be supported in the near future?

This looks promising

**Comment by whxaxes** [comment]
@dmbekker

**Comment by whxaxes** [comment]
@dmbekker  I'm so busy recently. I will update immediately after finishing it.

**Comment by dmbekker** [comment]
@whxaxes No problem :)

**Comment by Vaultrex** [comment]
he never updated it..
